name: Build project

on: push

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup caching
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: cache-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            cache-
      - name: Install dependencies
        run: |
          yarn
      - name: Lint project
        run: |
          yarn lint
      - name: Build project
        run: |
          yarn build
          yarn start
